CREATE TABLE IF NOT EXISTS messages (
    id SERIAL PRIMARY KEY,  
    sender_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE, 
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

